---
- name: Pull Docker image on Minikube host
  hosts: minikube
  tasks:
    - name: Pull Docker image
      community.docker.docker_image:
        name: "arijhabbechi/node-hello:latest"
        source: pull
      become: true
