apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello-deployment
  labels:
    app: node-hello
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node-hello
  template:
    metadata:
      labels:
        app: node-hello
    spec:
      containers:
        - name: node-hello
          image: arijhabbechi/node-hello:latest
          ports:
            - containerPort: 8080
